package main

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
)

func GenerateFake(gen *protogen.Plugin, file *protogen.File) {
	// rpc가 있는 서비스만 필터링
	hasRPCService := false
	hasEmptyMessage := false

	// 먼저 Empty 메시지 사용 여부와 RPC 서비스 존재 여부 체크
	for _, service := range file.Services {
		if len(service.Methods) > 0 {
			hasRPCService = true
			// Empty 메시지 사용 체크
			for _, method := range service.Methods {
				if method.Output.Desc.FullName() == "google.protobuf.Empty" ||
					method.Input.Desc.FullName() == "google.protobuf.Empty" {
					hasEmptyMessage = true
					break
				}
			}
		}
		if hasEmptyMessage {
			break
		}
	}

	if !hasRPCService {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_fake.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-fake. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// Import section
	g.P("import (")
	g.P(`    "github.com/ao-labs/protoc-gen-fake/pkg/fake"`)
	if hasEmptyMessage {
		g.P(`    emptypb "google.golang.org/protobuf/types/known/emptypb"`)
	}
	g.P(")")
	g.P()

	for _, service := range file.Services {
		if len(service.Methods) == 0 {
			continue
		}

		g.P("// Default responses for ", service.GoName)
		g.P("var Default", service.GoName, "Responses = map[string]fake.Response{")

		for _, method := range service.Methods {
			g.P(`    "`, buildMethodPath(service, method), `": {`)
			g.P(`        Method: "`, buildMethodPath(service, method), `",`)
			if method.Output.Desc.FullName() == "google.protobuf.Empty" {
				g.P(`        Response: &emptypb.Empty{},`)
			} else {
				g.P(`        Response: &`, method.Output.GoIdent.GoName, `{`)
				generateDefaultResponseFields(g, method.Output)
				g.P("        },")
			}
			g.P("    },")
		}

		g.P("}")
		g.P()
	}
}

func generateDefaultResponseFields(g *protogen.GeneratedFile, msg *protogen.Message) {
	for _, field := range msg.Fields {
		// Skip if field is oneof
		if field.Oneof != nil {
			continue
		}

		// Generate value
		value := getDefaultValueForField(field)
		if value != "" {
			g.P("            ", field.GoName, ": ", value, ",")
		}
	}
}

func buildMethodPath(service *protogen.Service, method *protogen.Method) string {
	return fmt.Sprintf("/%s.%s/%s", service.Desc.Parent().FullName(), service.GoName, method.GoName)
}
